name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: ['7.4']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Dependencies
        run: composer install --dev

      - name: Run tests
        run: ./vendor/bin/phpunit tests
